#!/bin/sh -e
#
# One timer, rtimer_run_next is called from different places
#

#----- Fire in idle -----------------------------------------------------------


./run "one timer, firing in idle" <<EOF
init:
	RA(100);
probe:
	rtimer_run_next();
expect:
	S(A,100)T(A,100)
EOF


#----- Fire from interrupt ----------------------------------------------------


./run "one timer, fired by interrupt" <<EOF
init:
	RA(100);
probe:
	advance(200);
	rtimer_run_next();
expect:
	S(A,100)T(A,100)
	S(A,100)T(A,200)
	S(A,100T(A,200))
EOF
